[package]
name = "rust-nostr-examples"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
nostr = "0.42.1"
nostr-sdk = "0.42.0"
serde_json = "1.0.140"
tokio = "1.45.1"
