[package]
name = "rust-nostr-examples"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
nostr = "0.42.1"
serde_json = "1.0.140"
tokio = "1.45.1"
tungstenite = { version = "0.20", features = ["rustls-tls-webpki-roots"] }
